### ISSUE TITLE
The game does not respond to the mod

### ISSUE THREAD

**Issue by ReusAg** [HAHAYOUDEAD/Personality#1]
I extract files to the mods folder, but the mod does not work and does not appear in the modsettings, what im doing wrong? I have other mods installed that work fine.
Game Version 2.06. MelonLoader 0.6.0 instaled.

**Comment by HAHAYOUDEAD** [comment]
Sorry I wasn't available for a few days. Did you figure it out? If not, could you throw your MelonLoader log into our TLD Modding discord, so we could check what could go wrong?
https://discord.com/invite/nb2jQez
