### ISSUE TITLE
Character change of gender upon loading the mod

### ISSUE THREAD

**Issue by bretttmercier** [HAHAYOUDEAD/Personality#2]
Upon first loading a save with your mod active, the character gender is changed from male to female. After saving the game, the change is permanent. Loading other saves create the same result. After disabling the mod, the character remains female if a save was made. If no save was made after using the mod, the character is back to being male.
Any idea about what is going on, and if there is a way to reverse this on a savegame?

**Comment by HAHAYOUDEAD** [comment]
that's how it is currently. You can change character in mod's settings, or via console if mod is uninstalled(voice_male is the command)
